[INFO][0][<module>] Linux derecho3 5.14.21-150400.24.18-default #1 SMP PREEMPT_DYNAMIC Thu Aug 4 14:17:48 UTC 2022 (e9f7bfc) x86_64 x86_64
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB (2.7)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/numpy (1.23.5)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/matplotlib (3.6.3)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/netCDF4 (1.6.2)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/cf_units (3.1.1)
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/sympy (1.12)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/mpi4py (3.1.4)
[INFO][0][<module>] 2024-06-10 03:57:21.143709
[DEBUG][0][extractTimeSeries][4x5_out_of_the_box] Could not find [RAIN] in the model results
[DEBUG][0][WorkConfront][TerrestrialWaterStorageAnomaly/GRACE][4x5_out_of_the_box]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfTWSA.py", line 147, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfTWSA.py", line 85, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][WorkConfront][Albedo/GEWEX.SRB][4x5_out_of_the_box_ann]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/FATES_calibration/ILAMB_data/DATA/rsds/GEWEX.SRB/rsds_0.5x0.5.nc'

[DEBUG][0][WorkConfront][Albedo/GEWEX.SRB][4x5_out_of_the_box]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/FATES_calibration/ILAMB_data/DATA/rsds/GEWEX.SRB/rsds_0.5x0.5.nc'

[INFO][0][MakeComparable][SurfaceNetSWRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[INFO][0][AnalysisMeanStateSpace][rsns] Bias scored using Collier2018
[INFO][0][confront][SurfaceNetSWRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Success
[DEBUG][0][extractTimeSeries][4x5_out_of_the_box] Could not find [rsds] in the model results
[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/GEWEX.SRB][4x5_out_of_the_box]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][AnalysisMeanStateSites][rsns] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSites][rsns] RMSE scored using Collier2018
[INFO][0][confront][SurfaceNetSWRadiation/WRMC.BSRN][4x5_out_of_the_box_ann] Success
[DEBUG][0][extractTimeSeries][4x5_out_of_the_box] Could not find [rsds] in the model results
[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/WRMC.BSRN][4x5_out_of_the_box]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][MakeComparable][SurfaceUpwardLWRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[INFO][0][AnalysisMeanStateSpace][rlus] Bias scored using Collier2018
[INFO][0][confront][SurfaceUpwardLWRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Success
[DEBUG][0][extractTimeSeries][4x5_out_of_the_box] Could not find [rlus,FIRE] in the model results
[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/GEWEX.SRB][4x5_out_of_the_box]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][AnalysisMeanStateSites][rlus] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSites][rlus] RMSE scored using Collier2018
[INFO][0][confront][SurfaceUpwardLWRadiation/WRMC.BSRN][4x5_out_of_the_box_ann] Success
[DEBUG][0][extractTimeSeries][4x5_out_of_the_box] Could not find [rlus,FIRE] in the model results
[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/WRMC.BSRN][4x5_out_of_the_box]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][MakeComparable][SurfaceNetLWRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[INFO][0][AnalysisMeanStateSpace][rlns] Bias scored using Collier2018
[INFO][0][confront][SurfaceNetLWRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Success
[DEBUG][0][extractTimeSeries][4x5_out_of_the_box] Could not find [FLDS] in the model results
[DEBUG][0][WorkConfront][SurfaceNetLWRadiation/GEWEX.SRB][4x5_out_of_the_box]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][AnalysisMeanStateSites][rlns] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSites][rlns] RMSE scored using Collier2018
[INFO][0][confront][SurfaceNetLWRadiation/WRMC.BSRN][4x5_out_of_the_box_ann] Success
[DEBUG][0][extractTimeSeries][4x5_out_of_the_box] Could not find [FLDS] in the model results
[DEBUG][0][WorkConfront][SurfaceNetLWRadiation/WRMC.BSRN][4x5_out_of_the_box]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][MakeComparable][SurfaceNetRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[INFO][0][AnalysisMeanStateSpace][rns] Bias scored using Collier2018
[INFO][0][confront][SurfaceNetRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Success
[DEBUG][0][extractTimeSeries][4x5_out_of_the_box] Could not find [FSDS] in the model results
[DEBUG][0][WorkConfront][SurfaceNetRadiation/GEWEX.SRB][4x5_out_of_the_box]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][AnalysisMeanStateSites][rns] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSites][rns] RMSE scored using Collier2018
[INFO][0][confront][SurfaceNetRadiation/WRMC.BSRN][4x5_out_of_the_box_ann] Success
[DEBUG][0][extractTimeSeries][4x5_out_of_the_box] Could not find [FSDS] in the model results
[DEBUG][0][WorkConfront][SurfaceNetRadiation/WRMC.BSRN][4x5_out_of_the_box]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][MakeComparable][SurfaceDownwardLWRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[INFO][0][AnalysisMeanStateSpace][FLDS] Bias scored using Collier2018
[INFO][0][confront][SurfaceDownwardLWRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Success
[DEBUG][0][extractTimeSeries][4x5_out_of_the_box] Could not find [FLDS,rlds] in the model results
[DEBUG][0][WorkConfront][SurfaceDownwardLWRadiation/GEWEX.SRB][4x5_out_of_the_box]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][AnalysisMeanStateSites][FLDS] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSites][FLDS] RMSE scored using Collier2018
[INFO][0][confront][SurfaceDownwardLWRadiation/WRMC.BSRN][4x5_out_of_the_box_ann] Success
[DEBUG][0][extractTimeSeries][4x5_out_of_the_box] Could not find [FLDS,rlds] in the model results
[DEBUG][0][WorkConfront][SurfaceDownwardLWRadiation/WRMC.BSRN][4x5_out_of_the_box]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][modelPlots][TerrestrialWaterStorageAnomaly/GRACE][4x5_out_of_the_box_ann] Success
[INFO][0][modelPlots][SurfaceNetSWRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Success
[INFO][0][modelPlots][SurfaceNetSWRadiation/WRMC.BSRN][4x5_out_of_the_box_ann] Success
[INFO][0][modelPlots][SurfaceUpwardLWRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Success
[INFO][0][modelPlots][SurfaceUpwardLWRadiation/WRMC.BSRN][4x5_out_of_the_box_ann] Success
[INFO][0][modelPlots][SurfaceNetLWRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Success
[INFO][0][modelPlots][SurfaceNetLWRadiation/WRMC.BSRN][4x5_out_of_the_box_ann] Success
[INFO][0][modelPlots][SurfaceNetRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Success
[INFO][0][modelPlots][SurfaceNetRadiation/WRMC.BSRN][4x5_out_of_the_box_ann] Success
[INFO][0][modelPlots][SurfaceDownwardLWRadiation/GEWEX.SRB][4x5_out_of_the_box_ann] Success
[INFO][0][modelPlots][SurfaceDownwardLWRadiation/WRMC.BSRN][4x5_out_of_the_box_ann] Success
[DEBUG][0][generateHtml][TerrestrialWaterStorageAnomaly/GRACE][Benchmark] 'global' not in region list = []
